spring.application.name=user-service
jwt.secretKey = dlagvlnfalkfj3oi43io524oi4io2fdsvknsddfn34oi55o5u3rgjkdfngdf23432tgregfdfdgfsldkgdfsglsd23323rfedsv

server.servlet.context-path=/users
server.port=9020

#DB Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/usersDB
spring.datasource.username=postgres
spring.datasource.password=force123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


